<a href="https://colab.research.google.com/github/CarlBayking/LinearAlgebra/blob/main/Assignment6_Bayking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Linear Algebra For ECE





Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamental of matrices, we'll try to do the same operations with matrices and even more.

### Objectives

at the end of this activity you will be able to:


1.   Be familiar with the fundamental matrix operations
2.   Apply the operations to solve intermediate equations
3.   Apply Matrix Algebra in engineering solutions



### Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Transposition

one of the fundamental operations in matrix algebra in Transposition. the transpose of a matrix is done by flipping the values of its elements over its diagonal. with this, the rows and columns from the original matrix will be switched. so for a matrix $A$ is denoted as matrix $A^T$.
For Example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$




$$A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 & -3 \\ 5 & 0 & 3\end{bmatrix}$$


In [ ]:
A= np.array([
    [1, 2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [1, 2, 3, 4],
              [1, 0, 2, 1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

### Try to Create your own matrix (you can try non-square matrix to test transposition)

In [ ]:
Carl= np.array([
    [8, 2, 7, 1],
    [9, 1, 2, 5],
    [5, 2, 1, 0],
])
Carl.shape

(3, 4)

In [ ]:
np.transpose(Carl).shape

(4, 3)

In [ ]:
Carl.T.shape

(4, 3)

In [ ]:
CarlT = Carl.T
CarlT

array([[8, 9, 5],
       [2, 1, 2],
       [7, 2, 1],
       [1, 5, 0]])

### Dot Product

-If you recall Dot product from Labratory Activity before, We will try to implement the same operations with matrices. In matrix dot product we are going to get the sum of products of the vectors by row column parts so if we have 2 matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X ,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X, Y)

array([[3, 4],
       [2, 2]])

try

In [ ]:
J = np.array([
    [-1,2,3],
    [3,1,5],
    [8,9,0]
])
C = np.array([
    [-1,0,9],
    [2,2,9],
    [9,9,9]
])

In [ ]:
np.dot(J,C)

array([[ 32,  31,  36],
       [ 44,  47,  81],
       [ 10,  18, 153]])

In [ ]:
C.dot(J)

array([[ 73,  79,  -3],
       [ 76,  87,  16],
       [ 90, 108,  72]])

In [ ]:
np.matmul(J,C)

array([[ 32,  31,  36],
       [ 44,  47,  81],
       [ 10,  18, 153]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [2,4],
    [5,-2],
    [0,1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
              [0,1,1],
              [1,2,2]
              
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
X = np.array([
              [1,2,3,0]
])
Y = np.array([
              [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
A @ C

array([[ 4, 10, 10],
       [-2,  1,  1],
       [ 1,  2,  2]])

In [ ]:
B @ C

array([[ 1,  3,  3],
       [ 3,  9,  9],
       [-2, -5, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X @ Y.T

array([[13]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

### Try Your Own Matrix Code

In [ ]:
L = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
M = np.array([
              [9,8,7],
              [6,5,4],
              [9,2,9]
])
N = np.array([
              [4,32,9],
              [9,5,1],
              [9,9,-9]
])
print(L.shape)
print(M.shape)
print(N.shape)

(3, 3)
(3, 3)
(3, 3)


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
L.dot(np.eye(3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
np.array_equal(L@M, M@L)

False

In [ ]:
James = L @ (M @ N)
James

array([[ 786, 2034,   78],
       [2019, 5103,  231],
       [3252, 8172,  384]])

In [ ]:
Carl = L @ M
Carl

array([[ 48,  24,  42],
       [120,  69, 102],
       [192, 114, 162]])

In [ ]:
Bayking = (L @ M) @ N
Bayking

array([[ 786, 2034,   78],
       [2019, 5103,  231],
       [3252, 8172,  384]])

In [ ]:
np.array_equal(James, Carl)

False

In [ ]:
np.array_equiv(James, Bayking)

True

In [ ]:
np.eye(L)

TypeError: ignored

In [ ]:
L @ James

array([[ 14580,  36756,   1692],
       [ 32751,  82683,   3771],
       [ 50922, 128610,   5850]])

In [ ]:
z_mat = np.zeros(L.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = L.dot(np.zeros(L.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(z_mat, a_dot_z)

True

In [ ]:
null_mat = np.empty(L.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

###$ Determinant$

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
             [1,4],
              [0,3] 
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
B = np.array([
              [1, 5, 2],
              [3, -1, -1],
              [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

In [ ]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

### $Inverse$

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
              [1, 7],
              [-3, 5]
])
np.array(M @ np.linalg.inv(M), dtype=int )

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [ ]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

### $ACTIVITY:$

### $TASK # 1:$
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

$#1$

In [ ]:
(1) ## A.B =/= to B.A 
A = np.array([
              [1,2,3,4],
              [4,5,6,7],
              [7,8,9,0],
              [4,3,2,1]
])
B = np.array([
              [9,8,7,6],
              [6,5,4,3],
              [9,2,9,0],
              [1,2,3,4]
])

print(A.shape)
print(B.shape)
James = A @ B
Bayking = B @ A

(4, 4)
(4, 4)


In [ ]:
np.array_equiv(James, Bayking)

False

$#2$

In [ ]:
(2) ## A@(B@C) = (A@B)@C
A_2 = np.array([
              [1,2,3,4],
              [4,5,6,7],
              [72,8,8,0],
              [1,3,2,9]
])
B_2 = np.array([
              [1,71,2,96],
              [9,1,2,6],
              [9,2,9,0],
              [1,2,3,4]
              
])
C_2 = np.array([
              [1,2,3,4],
              [5,6,7,8],
              [1,0,9,9],
              [1,2,3,4]
])
print(A_2.shape)
print(B_2.shape)
print(C_2.shape)
J_2 = A_2 @ (B_2 @ C_2)
B_2 = (A_2 @ B_2) @ C_2

(4, 4)
(4, 4)
(4, 4)


In [ ]:
J_2

array([[  654,   870,  1536,  1797],
       [ 2220,  2994,  4698,  5565],
       [33088, 45168, 59568, 71880],
       [  738,   986,  1764,  2065]])

In [ ]:
B_2

array([[  654,   870,  1536,  1797],
       [ 2220,  2994,  4698,  5565],
       [33088, 45168, 59568, 71880],
       [  738,   986,  1764,  2065]])

In [ ]:
np.array_equiv(J_2, B_2)

True

$#3$

In [ ]:
(3) ## A@(B+C) = A@B + A@C
A = np.array([
              [1,2,3,4],
              [4,5,6,7],
              [7,8,9,0],
              [4,3,2,1]
])
B = np.array([
              [9,8,7,6],
              [6,5,4,3],
              [9,2,9,0],
              [1,2,3,4]
              
])
C = np.array([
              [1,2,3,4],
              [5,6,7,8],
              [1,0,9,9],
              [1,2,3,4]
])
print(A.shape)
print(B.shape)
print(C.shape)
James = A @ (B + C)
Bayking = A @ B + A @ C
James

(4, 4)
(4, 4)
(4, 4)


array([[ 70,  54, 110,  91],
       [169, 135, 245, 205],
       [248, 176, 320, 239],
       [ 95,  81, 115,  99]])

In [ ]:
Bayking

array([[ 70,  54, 110,  91],
       [169, 135, 245, 205],
       [248, 176, 320, 239],
       [ 95,  81, 115,  99]])

In [ ]:
np.array_equal(James, Bayking)

True

$#4$

In [ ]:
(4) ##(B+C)@A = B@A + C.A
A = np.array([
              [1,2,3,4],
              [9,9,8,8],
              [1,2,3,4],
              [1,1,1,1]
])
B = np.array([
              [9,8,7,6],
              [2,0,1,2],
              [1,2,3,4],
              [1,2,3,4]
              
])
C = np.array([
              [1,4,2,3],
              [5,6,7,8],
              [1,0,9,9],
              [7.5,9,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)
J_4 = (B + C) @ A
B_4 = B @ A + C @ A
J_4

(4, 4)
(4, 4)
(4, 4)


array([[136. , 155. , 162. , 181. ],
       [ 79. ,  94. , 103. , 118. ],
       [ 45. ,  59. ,  71. ,  85. ],
       [117.5, 130. , 131.5, 144. ]])

In [ ]:
B_4

array([[136. , 155. , 162. , 181. ],
       [ 79. ,  94. , 103. , 118. ],
       [ 45. ,  59. ,  71. ,  85. ],
       [117.5, 130. , 131.5, 144. ]])

In [ ]:
np.array_equal(J_4 , B_4)

True

$#5$

In [ ]:
(5) ## A @ I = A
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
A_5 = np.array ([
                 [8,7,6,5],
                 [1,9,0,9],
                 [7,7,7,7],
                 [1,2,9,8]
])

In [ ]:
A_5.dot(np.identity(4))

array([[8., 7., 6., 5.],
       [1., 9., 0., 9.],
       [7., 7., 7., 7.],
       [1., 2., 9., 8.]])

In [ ]:
np.array_equiv(A_4 , np.identity(4) @ A_4)

True

$#6$

In [ ]:
(6) ## A @ ∅ = ∅
A_6 = np.array([
                [96,97,98,99],
                [99,99,99,99],
                [100,10000,100000,100000],
                [1,2,3,4]
])
print(A_6.shape)

(4, 4)


In [ ]:
np.zeros(A_6.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
null_mat = np.empty(A_6.shape , dtype=float)
null = np.array(null_mat,dtype=float)
print(null)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
A_6.dot(np.zeros(A_6.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equiv(A @ np.zeros(A_6.shape), null)

True

### $CONCLUSION:$

Basically, the laboratory experiment's goals were satisfied because we were able to implement the 6 matrix multiplication property. Using the phyton fundamentals that were taught to us in our earlier experiments, we were able to complete prove ,implement and run the 6 matrix properties and its result is as expected.  

Matrixes are important not only in mathematics, but also in everyday life. Matrices can also be used to represent real-world data like the world's population or a country's population and many more. They're used to make graphs, generate statistics, and perform scientific investigations and research across a wide range of topics. 
